### PR TITLE
Fix deprecated Python timing in benchmark & give more error info.

### PR DESCRIPTION
**Pull request by billyquith**
- Note: process_time gives CPU time used and perf_counter is absolute time used.
- Looks to have noise of about 1-2%.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
I already sent a PR #796 .

**Comment by billyquith** [comment]
Ok. I was fixing locally. You used `perf_counter`, but I think `process_time` should be more accurate.

**Comment by ChayimFriedman2** [comment]
Even the name says otherwise.

**Comment by billyquith** [comment]
According to the docs:

> time.perf_counter() → float
> Return the value (in fractional seconds) of a performance counter, i.e. a clock with the highest available resolution to measure a short duration. **It does include time elapsed during sleep** and is system-wide. The reference point of the returned value is undefined, so that only the difference between the results of consecutive calls is valid.
> 
> time.process_time() → float
> Return the value (in fractional seconds) of the sum of the system and user CPU time of the current process. **It does not include time elapsed during sleep**. It is process-wide by definition. The reference point of the returned value is undefined, so that only the difference between the results of consecutive calls is valid.

https://docs.python.org/3.8/library/time.html?highlight=perf_counter#time.perf_counter

We're not interested in non-process time. Unless the Python docs are wrong, process_time() measures the time the process spent, no?

**Comment by ChayimFriedman2** [comment]
You're right.

**Comment by billyquith** [comment]
Any reason not to merge this? I keep having to re-apply in branches.

**Comment by ChayimFriedman2** [comment]
@billyquith I have many PRs that weren't merged yet 😄 Let's not pressure @ruby0x1 .

**Comment by ruby0x1** [comment]
I'm working through 0.4 stuff atm and will check on these soon.

**Comment by ChayimFriedman2** [comment]
I'm waiting with patience 😺

**Comment by billyquith** [comment]
Thanks!

**Pull request merged**
