### PR TITLE
Add documentation for Fiber.transfer methods

### PR DESCRIPTION
**Pull request by fermian**
This patch adds documentation for Fiber.transfer methods (`Fiber.transfer` and `Fiber.transfer(value)`)

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
I think it's good to focus a little bit more in the differences from `.call()`.

**Comment by fermian** [comment]
> I think it's good to focus a little bit more in the differences from `.call()`.

Is it necessary? Wren's [concurrency page](https://wren.io/concurrency.html#transferring-control) already explains the difference.

**Comment by ChayimFriedman2** [comment]
Hmm. Didn't see that.

**Comment by ruby0x1** [comment]
Thanks @fermian, I changed the examples a bit and documented transferError as well.

**Pull request merged**
