### PR TITLE
Add smartmatch operators ~~ and !~

### PR DESCRIPTION
**Pull request by cxw42**
In case you'd like to give #989 a try, here you go!  All tests pass.  Initial benchmark results:

```
api_call - wren                .......... 0.10s 0.0013  87.26% relative to baseline
api_foreign_method - wren      .......... 0.53s 0.0121 103.88% relative to baseline
binary_trees - wren            .......... 0.32s 0.0068 104.63% relative to baseline
binary_trees_gc - wren         .......... 1.52s 0.0192 101.55% relative to baseline
delta_blue - wren              .......... 0.28s 0.0055  96.72% relative to baseline
fib - wren                     .......... 0.32s 0.0070  99.13% relative to baseline
fibers - wren                  .......... 0.07s 0.0013 104.20% relative to baseline
for - wren                     .......... 0.13s 0.0040 102.31% relative to baseline
method_call - wren             .......... 0.18s 0.0045  94.23% relative to baseline
map_numeric - wren             .......... 1.50s 0.0062 100.91% relative to baseline
map_string - wren              .......... 0.15s 0.0012  99.20% relative to baseline
string_equals - wren           .......... 0.32s 0.0056  98.29% relative to baseline
```

I haven't had a chance to analyze yet.  That `api_call` one is strange to me.

### CODE REVIEW

**Comment by mhermier** [comment]
Swap opcode implementation lack the debugger code.

`obj !~ fn` has some meaning as inverting the result of the function. So it should be `{ !fn.call(obj) }`.

Documentation is missing, but can wait a little.

**Comment by cxw42** [comment]
@mhermier Thanks for reviewing!  Debugger and `Fn.!~(_)` fixed.  I agree about the documentation and plan to add it later.

**Comment by cxw42** [comment]
(Crossposting https://github.com/wren-lang/wren/issues/956#issuecomment-834358728) Shall I close this in favor of a combination PR that does both switch and smartmatch?

**Comment by cxw42** [comment]
Closing in favor of #1009

**Pull request closed without merging**
