### PR TITLE
Don't use `strtoll()` with explicit base to parse hex, instead use `strtod()`

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
`strtod()` automatically recognizes the `0x` and converts to hex

This has two advantages:
 1. Simplify code (no need of argument `isHex` to `makeNumber`, no `if`)
 2. Allow numbers larger than `long long` if they fit into `double`

### CODE REVIEW

**Comment by mhermier** [comment]
Seems to be ok and POSIX compliant. In addition it will detect lack of
precision better.

**Comment by ChayimFriedman2** [comment]
It's standard compliant - C11 &sect;7.22.1.3 _The `strtod`, `strtof`, and `strtold` functions_:

> The expected form of the subject sequence is an optional plus or minus sign, then one of
the following:
— a nonempty sequence of decimal digits optionally containing a decimal-point
character, then an optional exponent part as defined in &sect;6.4.4.2;
— **a `0x` or `0X`, then a nonempty sequence of hexadecimal digits optionally containing a
decimal-point character, then an optional binary exponent part as defined in &sect;6.4.4.2;**
— `INF` or `INFINITY`, ignoring case
— `NAN` or `NAN(n-char-sequenceopt)`, ignoring case in the `NAN` part, where:
```
n-char-sequence:
digit
nondigit
n-char-sequence digit
n-char-sequence nondigit
```

(It's also in C98, don't worry. I just don't want to search the paper now).

**Comment by mhermier** [comment]
After that change pass, I wonder if it can be interesting to add
exponential notation to the language or it would be overkill...

**Comment by ChayimFriedman2** [comment]
We already have `e+-<exponent>`???!!

**Comment by mhermier** [comment]
Yes there is, I meant about hexadecimal version, it seems
0x1.0123456ap-0123 is a thing to produce double in hex.

**Comment by ChayimFriedman2** [comment]
Oh, I assumed this what you meant 😄. This seems silly 😕, I really don't understand why `strtod()` supports that. Why use hex for something other than dealing with raw bits?

**Comment by mhermier** [comment]
I have no particular clue, maybe it is history or serialisation for NaN. It
may need to be confirmed, but it may only allow raw bits for that it does
not loose precision

**Comment by mhermier** [comment]
Thinking at it again the solution is simple: 0x implies base 16. The thing
is  with integers, it maps with binary representation, and most people
assume/learn it is only that. But some math people really use base 16 to
reason and perform math.

**Comment by ChayimFriedman2** [comment]
Example of what wasn't allowed and now is allowed:
```wren
System.print(0x1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111)
```
This is too big to fit into `long long` but fits well into `double` (lossy).

**Comment by ChayimFriedman2** [comment]
Now noticed that `Num.fromString()` allows hex with fraction part:
```wren
System.print(Num.fromString("0x123456789.ABCDEF")) //> 4886718345.6711
```

**Comment by mhermier** [comment]
This patch merge is broken. Due to 1c5ac288312cb0111b5eb15b6e234781f1f8b8bb `parser->current` has to be changed to `parser->next`.
```
---------------------------- src/vm/wren_compiler.c ----------------------------
index 497978f7..5cb34063 100644
@@ -717,7 +717,7 @@ static void makeNumber(Parser* parser)
 {
   errno = 0;
 
-  parser->current.value = NUM_VAL(strtod(parser->tokenStart, NULL));
+  parser->next.value = NUM_VAL(strtod(parser->tokenStart, NULL));
   
   if (errno == ERANGE)
   {
```

**Comment by mhermier** [comment]
Pull request in #923.

**Pull request merged**
