### PR TITLE
Update gitignore

### PR DESCRIPTION
**Pull request by vladimyr**
Add VSCode project files and macOS specific stuff.

### CODE REVIEW

**Comment by bjorn** [comment]
Why close without any message? I guess the reasoning is, that these ignore rules are not Wren-specific and would be more suitable to put in the global `core.excludesfile`?

**Comment by ruby0x1** [comment]
No @bjorn, this was GitHub closing ALL pull requests due to a branch rename. We're waiting to hear back from support about redirecting the PRs to the right branch.

**Comment by vladimyr** [comment]
@bjorn All PRs got closed automatically by Github because the project owner renamed the main branch from `master` to `main`.

**Comment by bjorn** [comment]
Ok, thanks for the enlightenment! I'm confused though, why would `main` be a better name than `master`? Was this discussed anywhere? I would suggest sticking with the default.

**Comment by ruby0x1** [comment]
It was discussed in the discord yes. The default is going to change soon too, don't worry.

**Comment by bjorn** [comment]
> The default is going to change soon too, don't worry.

Huh, interesting. I better not share my opinion on this lest I be called a racist...

I do think `main` is a better name in general anyway, though I would have waited for the default to change rather than proactively changing the name and even deleting the `master` branch before moving the pull requests over. ;-)

**Pull request merged**
