### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by WeeKnightGames**
`absolutePrefixLength` doesn't compile under Windows.
The Windows terminal uses ASCII backspace.

### CODE REVIEW

**Comment by lagdotcom** [comment]
I just built this for Windows and noticed I also had to add this to cli/vm.c:
```c
#ifndef S_ISDIR
#define S_ISDIR(mode) (mode && S_IFDIR)
#endif
```

**Comment by mhermier** [comment]
Wrong fix, update libuv.

Le jeu. 24 janv. 2019 à 10:12, Paul Davies <notifications@github.com> a
écrit :

**Comment by lagdotcom** [comment]
I was using the version of libuv that the `update_deps.py` file downloads, is this wrong?

**Comment by mhermier** [comment]
Unless I'm mistaken the updater use a fixed old hash. So it is as old as
what you have, in master.

Le jeu. 24 janv. 2019 à 10:15, Paul Davies <notifications@github.com> a
écrit :

**Comment by ruby0x1** [comment]
No longer needed, the CLI repo should work as is now https://github.com/wren-lang/wren-cli/

**Pull request closed without merging**
