### PR TITLE
removing me from the mailing list

### PR DESCRIPTION
**Pull request by michal037**

### CODE REVIEW

**Comment by underscorediscovery** [comment]
Hi! The file you changed is unrelated to the mailing list. 

The mailing list is managed [here for the google group](https://groups.google.com/forum/#!forum/wren-lang) and [here is the email preferences](https://help.github.com/categories/receiving-notifications-about-activity-on-github/) information for Github. You can also check the top right of the repo for "Watch" or "Unwatch" depending that might be related.

**Comment by michal037** [comment]
corrected

**Comment by underscorediscovery** [comment]
Oh, I see! Are you sure? You contributed to Wren, so it's fine if it remains here. If you insist, I can remove it.

**Comment by michal037** [comment]
yes, I did not create enough.

**Comment by bjorn** [comment]
> yes, I did not create enough.

That may be the case by your standards, but there has been no minimum amount of work requirement for this list for anybody on that list.

Of course, the list is also pretty much redundant given that everybody who contributed even a single change are already listed on https://github.com/wren-lang/wren/graphs/contributors (including you), and all those people also get a "Contributor" badge on their comments here. The only way out of having contributed to Wren would be to filter your change out of the history. :-)

Not saying this PR shouldn't be merged, but at any point in the future somebody might decide that using `git shortlog -se` is a rather more reliable way of listing all authors, and you'd be back in.

**Comment by michal037** [comment]
Let it stay as it is. I understand, thank you for the explanation.

**Comment by underscorediscovery** [comment]
Thanks @bjorn that's what I was going to try and say.

**Pull request closed without merging**
