### PR TITLE
WIP wren/core: Add DEF_NUM_CONSTANT (with Num::infinity and Num::nan).

### PR DESCRIPTION
**Pull request by mhermier**

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
Do I understand correctly that you decided that `Object.same()` is eligible to own PR?

**Comment by mhermier** [comment]
Yes, the patch I have in preparation handles it differently by hardening `wrenNumToValue` and forcing any NaN to be a NaN singleton.
Patch set is for review, one open question is still what default value to use for the default NaN because AFAIK `NAN` is is a float and glibc macro extension.

**Comment by ChayimFriedman2** [comment]
`NAN` is float, but of course can be converted to a double. It _is_ standardized, but we can't use it since:

 - It's not required by the standard (compilers are free to omit it, although I guess they';; do that only if NaN isn't supported by the hardware).
 - Its value is not guaranteed (implementation defined).

**Comment by mhermier** [comment]
Added WREN_DOUBLE_NAN and moved conversion functions to "wren_math.h". Amalgamation needs to be checked in addition to review comments.

**Comment by ruby0x1** [comment]
I wonder if wren_math.h could be part of wren_utils.h instead, but that's not a big concern atm. Thanks!

**Pull request merged**
