### PR TITLE
[Experiment] Traits

### PR DESCRIPTION
**Pull request by clsource**
This is a simple experiment on adding Traits to Core Classes
See https://github.com/wren-lang/wren/issues/993#issuecomment-894682109

```js
String.trait("answer", 42)
String.trait("world", Fn.new{|self| "%(self) World"})

System.print("Hello".trait("world")) // expect: Hello World
System.print(String.trait("answer")) // expect: 42
```

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
I think this is worse that just do nothing. This calls method using strings, which is almost the worst thing we can do to add behavior to existing classes. Really, how is that better than an existing `class StringExt` with static methods?

**Comment by clsource** [comment]
> I think this is worse that just do nothing. This calls method using strings, which is almost the worst thing we can do to add behavior to existing classes. Really, how is that better than an existing `class StringExt` with static methods?

Because you can access the value directly without wrappers.
You can always implement a proxy that does not uses strings as method names.

**Comment by ChayimFriedman2** [comment]
I meant not a proxy, but something like:
```wren
class StringExt {
  static answer { 42 }
  static world(self) { "%(self) World" }
}
System.print(StringExt.world("Hello"))
System.print(StringExt.answer)
```
It is not less clear, saves the need for this change, and don't use magic strings (so, allowing more analysis etc.. The dynamism of strings is just not required here - you don't need to access/generate methods on-the-fly). As a bonus, it is also much more performant.

**Comment by mhermier** [comment]
Original idea seems broken. Among other problem, at best it supports
"static" traits only. Subclassing and/with composition seems a better
strategy where possible.

**Comment by clsource** [comment]
Supporting instance traits was implemented. If you call the trait on an instance it will assume a function and pass self as the first param. As shown in the "Hello".trait example

**Comment by ChayimFriedman2** [comment]
> Subclassing is not possible in core classes or foreign ones as far as i know

I would like to support subclassing foreign classes, but core classes are more complicated, and also less beneficial. This is because all instructions operating with primitives assumes a certain memory layout and changing that will make them much slower.

**Comment by clsource** [comment]
> > Subclassing is not possible in core classes or foreign ones as far as i know
> 
> I would like to support subclassing foreign classes, but core classes are more complicated, and also less beneficial. This is because all instructions operating with primitives assumes a certain memory layout and changing that will make them much slower.

Thats the reason I would like traits 👍

**Comment by CrazyInfin8** [comment]
I'm not sure if this is the greatest area to discuss this but I was wondering what if we implemented traits in a similar way to how Haxe does [Static Extensions](https://haxe.org/manual/lf-static-extension.html)?
```haxe
using Main.IntExtender;

class IntExtender {
  static public function triple(i:Int) {
    return i * 3;
  }
}

class Main {
  static public function main() {
    trace(12.triple());
  }
}
```
Haxe's rules for this are:
> 1. Both the literal `12` and the first argument of `triple` are known to be of type `Int`.
> 2. The class `IntExtender` is brought into context through `using Main.IntExtender`.
> 3. `Int` does not have a `triple` field by itself (if it had, that field would take priority over the static extension).

Wren doesn't know what type the parameters are, so we may need a different approach to adding extensions on another type.

I was thinking something along the lines of `using TargetExtender on Target` (syntax and keywords could definitely be different) like so:
```dart
class NumExtender {
    static triple { this * 3 }
}

using NumExtender on Num

12.triple // should return 36
```
The concept is that, for the rest of the scope after `using NumExtender on Num` was written, all static methods in `NumExtender` could be attached to `Num` (not added but *attached* somehow) as instance methods. If a method was called on `Num` that doesn't exist on `Num`, wren could check the list of attached methods for that scope and, if there happens to be a matching function signature, call the attached function instead.

Something may or may not be added to prevent using static fields in attached methods (instance fields are already syntactically incorrect so we don't need to worry about those) as to prevent these functions from mutating the class they are attached to. Alternatively they could be static fields from the extension class (so only affects `NumExtender` in an example like this)

Although this just seems to be syntax and ideas, I'm not sure if this is easily implementable in Wren right now without drastic changes. Just putting thoughts into word.

**Comment by clsource** [comment]
Updated the example using the Num class

```js
class NumExt {
    construct new(value) {
        _value = value
    }

    triple {
        return _value * 3
    }
}

Num.use(NumExt)

System.print(12.trait(NumExt).triple) // expect: 36
```

**Comment by clsource** [comment]
Another idea, but this would require more thinkering with the compiler
is abusing the Fibers.

If the `try` method returns an object or at least the string with the value and method that crashes the fiber. Then a simple map can be used to dispatch the proper method.

`NumExt` acts as wrapper that dispatch the methods if they are not found.

```js
class NumExt {

    static double (val) {
        return val * 2
    }

    static triple (val) {
        return val * 3
    }

    static extend(Klass, operations) {
        var result = operations.try()
        var methods = {
            "double": Fn.new {|val| NumExt.double(val)},
            "triple": Fn.new {|val| NumExt.triple(val)},
        }
        if (result is WrenRunTimeException) {
            var error = result
            result = methods[error.method].call(error.object)
        }
        return result
    }
}

NumExt.extend(Num, Fiber.new {
    return 2.double + 3.triple // expect: 13
})
```

**Comment by mhermier** [comment]
Seems overkill. Proxying or using object composition seems more valid
strategies.

**Pull request closed without merging**
