### PR TITLE
moved wrenReallocate from wren_vm.h to wren.h

### PR DESCRIPTION
**Pull request by Orcolom**
`WrenResolveModuleFn` requires the strings to be made with  `wrenReallocate`. resulting it needing to be accessible via `WREN_API`

moved to its declarations from `wren_vm.h` to `wren.h` next to the other `WREN_API` declarations

### CODE REVIEW

**Comment by mhermier** [comment]
Legitimate (thought I still would have preferred to avoid too leak internal symbols like this because of the API didn't used a `String` via the VM/fiber stack...)

**Comment by ChayimFriedman2** [comment]
I think the user should instead use `vm.config.reallocateFn()`.

**Comment by ChayimFriedman2** [comment]
Or just use `malloc()`, since it's guaranteed for the default allocator. No need to export this function.

**Comment by ruby0x1** [comment]
reminder @ChayimFriedman2 you can edit messages, no need to send N notifications within a minute.

> vm.config.reallocateFn().

The VM is an opaque type and the user API does not have internal access to the config.

**Comment by Orcolom** [comment]
cant do via malloc or own functions. wren frees the string via wrenReallocate and does some extra things to correctly garbage collect. I suspect by only using wrenReallocate (implicitly) on free. I would actually be breaking wren memory more.

Giving public access to the allocate function seems like a must with current implementations

**Comment by ruby0x1** [comment]
The root cause here is that `wrenResolveModuleFn` has this pattern of allocating via the vm allocate fn.

I don't think exposing the allocate function is an ideal direction, especially since this can be easily worked around by supplying an allocate function in the config and using it directly (even if copying the default one) instead of leaving it blank. 

I'm aware of your use case with the .net bindings, but I don't lean toward leaking internal details to solve a minor design issue with a single endpoint. 

So immediate term, you'll have to work around it best you can.
Thanks for the PR!

**Pull request closed without merging**
