### PR TITLE
added get method in sequence

### PR DESCRIPTION
**Pull request by clsource**
### **get**(predicate)

Iterates each element. It will return the first element that pass the `predicate`.
If no element is found it will return `null`.

```js
var numbers  = [1, 2, 3]
System.print(numbers.get {|item| item > 1}) //> 2

System.print([numbers.get {|item| item > 3}) //> null
```

### CODE REVIEW

**Comment by mhermier** [comment]
This change is not interesting, it is a variation of a more generic
`search` method that would return an iterator.

**Comment by ChayimFriedman2** [comment]
`search` is `where`.

**Comment by mhermier** [comment]
It has to be added (renamed as find to match c++), it is as trivial as
(unless I made a typo thinko):

```
find(predicate) { find(null, predicate) }

find(it, predicate) {
  while(it=iterate(it) && !predicate.call(iteratorValue(it)) {}
  return it
}
```

**Comment by ChayimFriedman2** [comment]
Why? What's the advantage of returning an iterator?

**Comment by mhermier** [comment]
What is the advantage of returning a value? `find` does not throw if the
value is not found (which is an error of the proposed implementation), and
the index is known. And that get is as trivial as using either
`list.iteratorValue(list.find(predicate))` or `list.filter(predicate)[0]`

**Comment by ChayimFriedman2** [comment]
Nice. It'll help to add a method `Sequence.getOrDefault(iterator, default)`.

**Comment by mhermier** [comment]
That explosion of methods that requires to be in `core` starts to be
problematic. There are fundamental methods, but some can really live
outside of `core`.

**Pull request closed without merging**
