### PR TITLE
Fix Xcode console

### LINKED ISSUE #554: Console on Xcode can't work
Colors and refresh can't work very well on Xcode. If you try type something like "var x = 1", you get:

```
\\/"-
 \_/   wren v0.1.0
[2K[30;1m
> [0m
[2Cvar[2K[30;1m
> [0m[0mv[0m
[3C[2K[30;1m
> [0m[0mva[0m
[4C[2K[30;1m
> [0m[36mvar[0m
[5C x[2K[30;1m
> [0m[36mvar[0m[0m [0m
[6C[2K[30;1m
...
```

I "fix" it erasing the function refreshLine and colors, but it is a workaround. What is the correct way to fix it?

### PR DESCRIPTION
**Pull request by macabeus**
Fix Xcode console. Also it adds a new static method on `Process` class: `getEnv()`. I used it to know if the RELP was opened on Xcode or not.

Closes #554 (and a topic in #553)

### CODE REVIEW

**Comment by Akaricchi** [comment]
I realize this PR is not really about this, but I think it's still worth pointing out:

>Gets the value of an environment variable. Returns a blank string if the environment variable does not exists.

That's not the right way to do this. An environment variable may exist and be set to an empty string. With this API it's impossible to distinguish it from a non-existent variable. I propose a dict-like object API instead, much like Python's `os.environ`.

**Comment by mhermier** [comment]
Considering how argument passing is done, getEnv should be part of Process and not platform. But if we go a little bit deeper in the rabbit hole, Process should have a method returning an object to the process env. That object would implement a minimal map behavior, and restrict key value pairs to strings only. That way we could have access to the real process env, and if the notion of process is extended, it can return a non system object representing the env.

For the other REPL fix, I'm not sure it is the right approach. Technically I would say that what you wrote is the SimpleRepl.
Not sure how correct it is, but I think refresh should be disabled when `!stdin.isRaw` while the ANSI code should be protected by a variable representing the level of supported ANSI terminal features.
Since I'm pretty sure Xcode implementation seems too dumb to have grabbed a terminal handle, or at least fake it correctly enough, we could disable the isRaw setting by env at construction, in a single consolidated code. Easier said than done, but terminal interaction always implies dirty hands and too many conditionals....

**Comment by macabeus** [comment]
@mhermier In addition of disable the refresh, we still need print the `> ` to have a difference between line typed by user and line of a result.
And, the history still doesn't work, and I really haven't any idea how to fix it (or maybe is better simply disable it).

Since the Xcode console has this differences, I think that is better it has a different class.

**Comment by macabeus** [comment]
@Akaricchi @mhermier I did what you suggested:

- [x] `getEnv` now returns a map with the format `[key: value]`, like Python's `os.environ`
- [x] Moved the `getEnv` static method to Process class
- [x] Disabled history on Xcode console

This method really should called `getEnv`? Or it should be rename it to a better name?
I didn't find any way to returns a map by C API, then I created a Wren function to map the array with environment values to a map.

**Comment by mhermier** [comment]
Considering what the API looks around, and prior art `environ` or `environment` sounds a better name then `getEnv` to me.
You should to do it manually the way compiler does. Creating the map add calling something like `_addCore` (which should really be renamed to `append`)

**Comment by Akaricchi** [comment]
I agree with @mhermier about calling it either `environ` or `environment` (and no parentheses in the signature). Ideally, the returned object shouldn't be a real map with an actual copy of the entire environment. Instead, I'd make it a map-like object with the same API, so that `Process.environ["foo"]` calls `getenv("foo")`, `Process.environ["foo"] = "bar"` calls `setenv("foo", "bar")`, etc. But that warrants a separate pull request at this point.

**Comment by mhermier** [comment]
Agreed with Alexey.

One minor subject that may need a separated discussion, how to handle
software/fake process in general and it's environment in particular, to
stay in the subject of this thread. I would say it should use a plain map,
to be able to pass strings/lists/maps/images/any kind of resources. This
would remove one of the most annoying barrier I have with any shell/program
intercommunication.

**Comment by macabeus** [comment]
@Akaricchi @mhermier I did what you suggested:

- [x] Renamed `getEnv` to `environ`
- [x] No parentheses in the signature

And is better that additional discussions in another pull request.

**Pull request closed without merging**
