### PR TITLE
Upgrade libuv from v1.10.0 to v1.35.0

### PR DESCRIPTION
**Pull request by vladimyr**
This PR updates `libuv` to the latest version supporting building using `gyp`. Additionally, build script has been altered to use `make` on macOS as suggested here: https://github.com/wren-lang/wren/issues/514#issue-306806601

### CODE REVIEW

**Comment by ruby0x1** [comment]
Wren 0.3.0 was released a few hours ago, which moves the CLI to it's [own repo](https://github.com/wren-lang/wren-cli/releases/tag/0.3.0) which has libuv 1.34.2 already, and includes a make project for mac (in addition to the xcode project).

Thanks for the PR, but this is already solved by the work for 0.3.0!

**Comment by vladimyr** [comment]
> Wren 0.3.0 was released a few hours ago, which moves the CLI to it's [own repo](https://github.com/wren-lang/wren-cli/releases/tag/0.3.0) which has libuv 1.34.2 already, and includes a make project for mac (in addition to the xcode project).

Wow, 😮 I cloned repo a few days ago and started tweaking it as a consequence of my effort to build Homebrew formula for wren CLI. Checked commit rate on the master branch, but I was dumb enough not to check out active PRs 🤦 
Anyway, I'm both surprised and thrilled to discover this 👍 Great work!

**PS** I would close it myself but I was too mesmerized by discovering all the changes. 😄

**Comment by ruby0x1** [comment]
No problem! The work for 0.3.0 was being [done in a branch](https://github.com/wren-lang/wren/tree/0.3.0-refactor), hence not much change on master.

**Comment by vladimyr** [comment]
Btw, is it ok to do a quick PR on the CLI repo to bump libuv to the latest possible version? Here, I went with v1.35.0 and all tests succeded. Had to stop there due to v1.36.0 dropping support for gyp but now when gyp is out of story I could try with the latest version? What do you think? 🤔

**Comment by ruby0x1** [comment]
I did a quick test with [1.38.0](https://github.com/libuv/libuv/releases) on Windows and it seemed to work fine, 
so let's do that version and test it out on other platforms. 

That's the latest stable, so if you want to PR that change that sounds good to me.
**Note** that we don't use gyp or anything, we vendor the source tree into the **`deps/libuv`** folder now.

I'd recommend deleting the contents of `include/` and `src/` inside that folder, then copy the latest, rather than just pasting on top. This makes sure that removed files are removed, and new ones are noticeable.

**Comment by ruby0x1** [comment]
Oh and make sure to update [version.md](https://github.com/wren-lang/wren-cli/blob/master/deps/libuv/version.md) in the libuv folder.

**Comment by vladimyr** [comment]
Thank you for taking time to write detailed instructions! Much appreciated! 👍

**Pull request closed without merging**
